#!/bin/bash

sudo killall --ignore-case -9 "/usr/bin/python"   
sudo killall --ignore-case -9 "python" 
sudo killall --ignore-case -9 "SCREEN"
sudo killall --ignore-case -9 "nova-api" 
sudo killall --ignore-case -9 "cinder-api"
sudo killall --ignore-case -9 "neutron-api"
sudo killall --ignore-case -9 "glance-api"
sudo killall --ignore-case -9 "quantum"
sudo killall --ignore-case -9 "heat-api"
sudo killall --ignore-case -9 "rabbitmq"
sudo killall --ignore-case -9 "dstat"
sudo killall --ignore-case -9 "keystone"
sudo killall --ignore-case -9 "ovsdb-server"
sudo killall --ignore-case -9 "ovs-vswitchd"
sudo killall --ignore-case -9 "apache2"
