#!/bin/bash

# Sa se scrie un script care implementeaza operatiile matematice de baza ( +, -, *,
# /, %). Scriptul va primi ca parametri doar operanzii. Scriptul afiseaza un meniu
# de unde se poate selecta una din operatiile disponibile. Daca utilizatorul
# selecteaza alta optiune, scriptul isi va incheia executia afisand un mesaj de
# terminare. Operatiile vor fi implementate prin functii scrise intr-un fisier separat.
# Scriptul va testa existenta fisierului de functii iar daca acesta exista il va incarca,
# altfel va afisa un mesaj de eroare. Pentru meniu trebuie scrisa o functie.
# Restrictii:
# - functia pentru afisarea meniului nu se scrie in fisierul ce contine functiile
# pentru operatii.
# - pentru implementarea meniului se va folosi o structura de control de tip
# case.
# - maxim 2 fisiere (scriptul principal si fisierul de functii matematice)


if [[ ! -f math ]]; then
  echo "Functions file not found!"
  exit 1
else
  . math
fi


menu () {
  echo Menu:
  echo -e '\t' 1-Add numbers
  echo -e '\t' 2-Subtract numbers
  echo -e '\t' 3-Multiply numbers
  echo -e '\t' 4-Divide numbers
  echo -e '\t' 5-Decimal part
  echo -e '\t' 0-exit

  read -p 'Option: ' opt


  case "$opt" in
0)
  exit 0;
  ;;
1)
  n="$(add "$1" "$2")"
  echo "$n"
  ;;
2)
  n="$(subtract "$1" "$2")"
  echo "$n"
  ;;
3)
  n="$(multiply "$1" "$2")"
  echo "$n"
  ;;
4)
  n="$(divide "$1" "$2")"
  echo "$n"
  ;;
5)
  n="$(modulo "$1" "$2")"
  echo "$n"
  ;;
*)
  echo "Invalid option"
  exit 1
esac
}

menu "$1" "$2"
